name: Build and Test ldsCtrlEst

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up vcpkg
      run: |
        rm -rf vcpkg
        git clone https://github.com/microsoft/vcpkg.git
        cd vcpkg
        ./bootstrap-vcpkg.sh  # Use .\bootstrap-vcpkg.bat on Windows

    - name: Set up dependencies
      run: |
        if [ "${{ runner.os }}" == "macOS" ]; then
          brew install cmake gfortran curl zip unzip tar build-essential
        elif [ "${{ runner.os }}" == "Linux" ]; then
          sudo apt-get install -y cmake gfortran pkg-config
        elif [ "${{ runner.os }}" == "Windows" ]; then
          choco install cmake git
        fi

    - name: Configure and build
      run: |
        mkdir build && cd build
        cmake ..
        cmake --build .

    - name: Run tests
      run: |
        cd build
        ctest
