name: Build and Test ldsCtrlEst

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Cache vcpkg directory
      uses: actions/cache@v3
      with:
        path: vcpkg
        key: vcpkg-${{ matrix.os }}-${{ hashFiles('vcpkg.json') }}
        restore-keys: vcpkg-${{ matrix.os }}-

    - name: Set up vcpkg
      env:
        VCPKG_DEFAULT_BINARY_CACHE: ${{ github.workspace }}/vcpkg_cache
      run: |
        if [ ! -d "vcpkg" ]; then
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          ./bootstrap-vcpkg.sh
        fi
      if: runner.os != 'Windows'

    - name: Set up vcpkg for Windows
      if: runner.os == 'Windows'
      shell: pwsh
      env:
        VCPKG_DEFAULT_BINARY_CACHE: ${{ github.workspace }}/vcpkg_cache
      run: |
        if (!(Test-Path -Path "vcpkg")) {
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          .\bootstrap-vcpkg.bat
        }

    - name: Cache vcpkg binary packages
      uses: actions/cache@v3
      with:
        path: ${{ github.workspace }}/vcpkg_cache
        key: vcpkg-binaries-${{ matrix.os }}-${{ hashFiles('vcpkg.json') }}
        restore-keys: vcpkg-binaries-${{ matrix.os }}-

    - name: Install dependencies using vcpkg
      env:
        VCPKG_DEFAULT_BINARY_CACHE: ${{ github.workspace }}/vcpkg_cache
      run: |
        mkdir -p $VCPKG_DEFAULT_BINARY_CACHE  # Ensure the cache directory exists
        ./vcpkg/vcpkg install --clean-after-build
      shell: bash

    - name: Install dependencies (Linux/macOS)
      if: runner.os != 'Windows'
      run: |
        if [ "${{ runner.os }}" == "macOS" ]; then
          brew install cmake gfortran
        elif [ "${{ runner.os }}" == "Linux" ]; then
          sudo apt-get update
          sudo apt-get install -y cmake gfortran
        fi

    - name: Install dependencies (Windows)
      if: runner.os == 'Windows'
      run: choco install cmake

    - name: Cache build directory
      uses: actions/cache@v3
      with:
        path: build
        key: build-${{ matrix.os }}-${{ hashFiles('CMakeLists.txt') }}
        restore-keys: build-${{ matrix.os }}-

    - name: Configure and build (All Platforms)
      run: |
        mkdir -p build && cd build
        cmake .. -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/install
        cmake --build . --config Release --parallel
      shell: bash

    - name: Install
      run: cmake --install build
      shell: bash

    - name: Run tests
      run: ctest --test-dir build -C Release
