name: Build Python Wheels

on:
  push:
    branches: [test]
  pull_request:
    branches: [test]
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies with vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: '${{ github.workspace }}/vcpkg'
          runVcpkgFormatString: "['install', '--triplet', '$[env.VCPKG_DEFAULT_TRIPLET]']"
          runVcpkgInstall: true

      - name: Build wheels (macOS & Linux)
        if: runner.os != 'Windows'
        uses: pypa/cibuildwheel@v2.16.2
        with:
          package-dir: python
          only: ${{ (matrix.os == 'macos-latest' && 'cp312-macosx_arm64') || 'cp312-manylinux_x86_64' }}
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}

      - name: Build wheels (Windows)
        if: runner.os == 'Windows'
        run: pipx run cibuildwheel --output-dir wheelhouse --only cp312-win_amd64 python
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}
          path: ./wheelhouse/*.whl
