name: Build Python Wheels

on:
  push:
    branches: [test]
  pull_request:
    branches: [test]
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest] # Focus on Linux only for debugging

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies with vcpkg (Linux)
        if: runner.os == 'Linux'
        run: |
          chmod +x vcpkg/bootstrap-vcpkg.sh
          ./vcpkg/bootstrap-vcpkg.sh
          ./vcpkg/vcpkg install --triplet=x64-linux

      - name: Verify vcpkg installation
        run: |
          ls -la vcpkg_installed/x64-linux/ || echo "vcpkg directory not found"
        shell: bash

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.2
        env:
          CMAKE_TOOLCHAIN_FILE: ${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake
          CIBW_BUILD: "cp311-*" # Build only Python 3.11 for faster iteration
          CIBW_SKIP: "pp*" # Skip PyPy builds (incompatible with pybind11)
          # Use older manylinux image for better glibc compatibility
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
          # Linux: Use pre-installed vcpkg dependencies from host
          CIBW_BEFORE_ALL_LINUX: |
            echo "=== Setting up manylinux2014 build environment ==="
            echo "Using vcpkg dependencies installed on host"
            ls -la /project/vcpkg_installed/x64-linux/ || echo "Host vcpkg directory not found"
            echo "Checking available devtoolsets:"
            ls -la /opt/rh/
            echo "=== Setting up devtoolset-9 for better pybind11 compatibility ==="
            # Force devtoolset-9 only (GCC 9.x is more compatible with pybind11)
            if [ -f /opt/rh/devtoolset-9/enable ]; then
              echo "Using devtoolset-9"
              source /opt/rh/devtoolset-9/enable
            else
              echo "devtoolset-9 not found, trying to install it"
              yum install -y devtoolset-9-gcc devtoolset-9-gcc-c++ || echo "Failed to install devtoolset-9"
              if [ -f /opt/rh/devtoolset-9/enable ]; then
                source /opt/rh/devtoolset-9/enable
              else
                echo "ERROR: devtoolset-9 required for pybind11 compatibility"
                exit 1
              fi
            fi
            echo "GCC version after devtoolset setup:"
            gcc --version
            echo "G++ version:"
            g++ --version
            echo "GLIBC version check:"
            ldd --version
            echo "Using header-only Armadillo for maximum manylinux compatibility"
          CIBW_ENVIRONMENT_LINUX: CMAKE_TOOLCHAIN_FILE=/project/vcpkg/scripts/buildsystems/vcpkg.cmake CMAKE_PREFIX_PATH=/project/vcpkg_installed/x64-linux LDSCTRLEST_BUILD_PYTHON=ON CIBW_LINUX=1 Python3_EXECUTABLE={python} Python3_INCLUDE_DIR={python_include} Python3_LIBRARY={python_library} VERBOSE=1 CC=gcc CXX=g++
          CIBW_BUILD_VERBOSITY_LINUX: 1
          CIBW_BEFORE_BUILD_LINUX: echo "CMAKE_TOOLCHAIN_FILE=$CMAKE_TOOLCHAIN_FILE" && echo "CMAKE_PREFIX_PATH=$CMAKE_PREFIX_PATH" && echo "LDSCTRLEST_BUILD_PYTHON=$LDSCTRLEST_BUILD_PYTHON" && echo "Python paths:" && echo "Python3_EXECUTABLE=$Python3_EXECUTABLE" && echo "Python3_INCLUDE_DIR=$Python3_INCLUDE_DIR" && echo "Python3_LIBRARY=$Python3_LIBRARY" && ls -la /project/vcpkg_installed/x64-linux/ || echo "vcpkg directory not found" && echo "Looking for gfortran libraries:" && find /usr -name "*gfortran*" 2>/dev/null || echo "gfortran not found" && find /opt -name "*gfortran*" 2>/dev/null || echo "gfortran not found in /opt" && echo "Checking glibc version:" && ldd --version
          CIBW_REPAIR_WHEEL_COMMAND_LINUX: |
            echo "=== Repairing wheel with auditwheel ==="
            echo "Wheel before repair: {wheel}"
            auditwheel show {wheel}
            # Try repair with specific glibc symbol exclusion if needed
            auditwheel repair -w {dest_dir} {wheel} --exclude libgfortran.so.5 --exclude libquadmath.so.0 || auditwheel repair -w {dest_dir} {wheel}
            echo "=== Repair completed ==="
          CIBW_TEST_COMMAND: |
            echo "=== Testing wheel import ==="
            echo "Python version:"
            python --version
            echo "Testing basic import:"
            python -c "import ldsctrlest; print('✅ Basic import successful!')"
            echo "Testing module access:"
            python -c "import ldsctrlest; print('Available modules:', dir(ldsctrlest)); print('✅ Module access successful!')"
            echo "Testing numpy integration:"
            python -c "import ldsctrlest; import numpy as np; print('NumPy version:', np.__version__); print('✅ NumPy integration successful!')"
        with:
          package-dir: python

      - name: List built wheels
        run: |
          ls -la wheelhouse/
          echo "Inspecting wheel contents:"
          unzip -l wheelhouse/*.whl
          echo "Looking for shared libraries:"
          unzip -Z wheelhouse/*.whl | grep -E '\.(so|dylib|dll)' || echo "No shared library files found"
        shell: bash

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}
          path: ./wheelhouse/*.whl
